# Generated by Django 4.2.7 on 2024-02-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrecord',
            options={'get_latest_by': 'date'},
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='absent',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='late',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='dailyrecord',
            name='remarks',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totalabsent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totallateness',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totalovertime',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employeestatus',
            name='totalundertime',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrecord',
            name='totalovertime',
            field=models.CharField(default='00:00:00', max_length=8),
        ),
    ]
